development:
  adapter: postgresql
  database: development
  pool: 5
  username: ecwilliams
  password:
  host: localhost

test:
  adapter: postgresql
  database: test
  pool: 5
  username: ecwilliams
  password:
  host: localhost
